# Generated by Django 4.2 on 2023-05-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'attribute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('attribute_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'attribute_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttributeUnit',
            fields=[
                ('attribute_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'attribute_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('warranty_months', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'request_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseAddress',
            fields=[
                ('warehouse_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'warehouse_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.product')),
                ('warehouse_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.warehouseaddress')),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.product')),
            ],
            options={
                'db_table': 'product_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('product_color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.product')),
            ],
            options={
                'db_table': 'product_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('product_attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.product')),
            ],
            options={
                'db_table': 'product_attribute',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='Catalog.ProductAttribute', to='Catalog.attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(through='Catalog.ProductColor', to='Catalog.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(through='Catalog.Warehouse', to='Catalog.warehouseaddress'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.CharField(max_length=255)),
                ('type_of_request', models.ForeignKey(db_column='type_of_request', on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.requesttype')),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.country'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.attributename'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Catalog.attributeunit'),
        ),
    ]
